# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://claudiasofiaC.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Claudia Chajon
# Description of the Site
description: full stack data scientist | data enthusiast | plant mom
# URL of Image of the Site
site-image: /assets/images/banner1.png
# Keywords of the Site
site-keywords: claudia chajon, data science, data visualization, machine learning, data analyst
# URL for the Image of custom Favicon
favicon-url: /assets/images/laptop.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.unsplash.com/photo-1648870283315-430ed67f817a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: claudia.chajon@gmail.com
facebook_username:
twitter_username:
instagram_username: guavacheesepuff
linkedin_username: claudia-chajon
github_username:  claudiasofiaC
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics:

# Disqus
disqus-shortname:

# Name of the Author
author-name: Claudia Chajon
# URL for the Image of the Author
author-image: /assets/images/prof_pic.png
# 60 Words About the Author
author-about: "Hi! I'm <strong>Claudia Chajon</strong>. I'm currently enjoying life by coding, crocheting, collecting plants and rowing in New York City.<br /><br />

I've had a somewhat unconventional path to data science but I wouldn't change a thing about what has brought me to this point. The learnign never stops. You can check out my work on my<a href='/blog'>personal blog</a>, where I apply my creative background to solve data problems.<br /><br />

I use my experience to foster creative environments that cultivate ideas big and small. From the start of my career, I've brought creative energy, originality, and a fresh approach to digital experiences.<br /><br />

I love to talk data, crochet and plants, please feel free to reach out and start a conversation!"
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: /#about

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-sitemap

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Excludes
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
